language: cpp
dist: xenial
compiler: gcc
sudo: true

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test # C++11
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-5 # C++11

# Xenial
services:
  - xvfb

# Trusty
# Start virtual X server
# before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start

script: 
 - ./build_test.sh
 - ./build_normal.sh


